### ISSUE TITLE
Return code when Error occurs

### ISSUE THREAD

**Issue by bamartos** [sepulworld/aptly_cli#157]
Hi,

Is it possible to get an exit code different than 0 when aplty_cli command failing? 

Cheers,

Vasilis

**Comment by sepulworld** [comment]
Can you share example command that fails with exit 0?

**Comment by bamartos** [comment]
Wow, thanks for the super first reply. 

I am trying actually to run some repo_upload commands:

`aptly-cli --server srv --port 8081 --no-config repo_upload --name my-non-existing-repo --dir dir-my-repo --file foo.deb`

It returns an error:

> repository with such name does not exist
> {"error":"local repo with name my-non-existing-repo not found"}

For this the exit code is 0 (echo $?)

Also for this command:

`aptly-cli --server srv --port 8081 --no-config repo_upload --name my-repo --dir dir-my-repo --file foo.deb`

the binary foo.deb doesnt exists so I get the expected message :

> Files that failed to upload... [dir-my-repo/foo.deb]
> File upload warning message[s]...             ["Unable to process ... foo.deb: no such file or directory"],"Added":[],"Removed":[]}}
> 

Based on the Warning (= Non-successful termination) shouldnt be better to get something different than 0 as exit code?

This feature can be really useful when you use CI/CD pipelines which should mark the task as failed in case of Warning/Errors like above

**Comment by sepulworld** [comment]
Thank you! Yeah, we can fix this to return proper exit code via some error handling. I’ll try find some time to add this in code soon
