### ISSUE TITLE
Incorrect encoding on Ruby 1.9.1

### ISSUE THREAD

**Issue by avongluck-r1soft** [sepulworld/aptly_cli#63]
Seeing this on Ruby 1.9.1.

```
# aptly-cli 
/usr/local/bin/aptly-cli:23:in `load': /var/lib/gems/1.9.1/gems/aptly_cli-0.1.5/bin/aptly-cli:28: invalid multibyte char (US-ASCII) (SyntaxError)
/var/lib/gems/1.9.1/gems/aptly_cli-0.1.5/bin/aptly-cli:28: invalid multibyte char (US-ASCII)
/var/lib/gems/1.9.1/gems/aptly_cli-0.1.5/bin/aptly-cli:28: syntax error, unexpected $end, expecting keyword_end
... would be created if it doesn’t exist.'
...                               ^
    from /usr/local/bin/aptly-cli:23:in `<main>'
```

Solution is to add the following to the aptly-cli script just below #!/usr/bin/env ruby

```
#!/usr/bin/env ruby
# encoding: utf-8
```

**Comment by sepulworld** [comment]
Thank you!  Testing fix now

**Comment by sepulworld** [comment]
Oh, this if for Ruby 1.9.1.  This version of Ruby has gone EOL a while back, but adding this doesn't appear to break any of the newer versions.  I added it and updated the gem to 0.1.6.  The Travis tests all pass

https://rubygems.org/gems/aptly_cli

Hope that helps out!
