### ISSUE TITLE
failedFiles vs FailedFiles

### ISSUE THREAD

**Issue by keithjpaulson** [sepulworld/aptly_cli#65]
I'm seeing:

`/opt/ruby/2.1.2/lib/ruby/gems/2.1.0/gems/aptly_cli-0.1.6/lib/aptly_repo.rb:123:in 'repo_upload': undefined method 'empty?' for nil:NilClass (NoMethodError)`

in aptly_repo.rb; code references json_response["failedFiles"], but I see FailedFiles if I run the API manually.

**Comment by sepulworld** [comment]
Thank you @keithjpaulson for the report.  I will take a look and write a fix and test for this bug

**Comment by sepulworld** [comment]
@keithjpaulson I merged the fixes and updated aptly_cli gem to 0.1.8

https://rubygems.org/gems/aptly_cli

Please update and validate fix for me

**Comment by keithjpaulson** [comment]
I got the 0.1.8 version on update, and it is performing repo-upload without issue (though json is printed, unsure if that is intended...but I don't mind seeing feedback)

$ aptly-cli repo_upload --dir test1 --name ssr-precise -trace
{"FailedFiles"=>[], "Report"=>{"Warnings"=>[], "Added"=>["mariadb-common_5.5.32+maria-1~precise_all added"], "Removed"=>[]}}

**Comment by sepulworld** [comment]
Thanks for confirming it works.  Yeah, it just returns the JSON response the is received from Aptly API.  

I opened up a new issue to improve CLI response output. https://github.com/sepulworld/aptly_cli/issues/68
